<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MNIDSK0016" ignored="3" name="Default test" tests="1" failures="1" timestamp="06 Sep 2018 09:23:45 GMT" time="0.029" errors="0">
  <testcase name="verifyAddCountry" time="0.006" classname="com.example.restTesto.Test1">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: verifyAddCountry([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=int, declaredAnnotations=[]}])
Arguments: [(java.lang.String) {&amp;quot;id&amp;quot;:5,&amp;quot;countryName&amp;quot;:&amp;quot;UK&amp;quot;,&amp;quot;population&amp;quot;:01201},(java.lang.String) 01201,(java.lang.String) UK]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: verifyAddCountry([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=int, declaredAnnotations=[]}])
Arguments: [(java.lang.String) {"id":5,"countryName":"UK","population":01201},(java.lang.String) 01201,(java.lang.String) UK]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAddCountry -->
  <testcase name="testGet" time="0.0" classname="com.example.restTesto.Test1">
    <ignored/>
  </testcase> <!-- testGet -->
  <testcase name="testPost" time="0.0" classname="com.example.restTesto.Test1">
    <ignored/>
  </testcase> <!-- testPost -->
  <testcase name="testGetBtId" time="0.0" classname="com.example.restTesto.Test1">
    <ignored/>
  </testcase> <!-- testGetBtId -->
</testsuite> <!-- Default test -->
